# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=15)),
                ('course_discription', models.TextField()),
                ('course_website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_name', models.CharField(max_length=30)),
                ('forum_created', models.DateTimeField()),
                ('forum_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField()),
                ('exam_category', models.CharField(choices=[('QZ', 'Quiz'), ('MS', 'Mid Semester'), ('ES', 'End Semester'), ('AS', 'Assignment')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('faculty_password', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('faculty_email', models.EmailField(blank=True, max_length=254)),
                ('extension', models.CharField(blank=True, max_length=15, null=True)),
                ('research_area', models.TextField(null=True)),
                ('Result', models.ManyToManyField(to='ucportal.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_detail', models.TextField()),
                ('company_technology', models.TextField()),
                ('company_salary', models.IntegerField()),
                ('company_contacts', models.TextField()),
                ('related_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucportal.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_document', models.FileField(upload_to='result_docs/%Y/%m/%d/')),
                ('result_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucportal.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('student_password', models.CharField(max_length=20)),
                ('student_ID', models.CharField(max_length=15)),
                ('date_of_birth', models.DateTimeField()),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('current_year', models.DateTimeField()),
                ('current_courses', models.ManyToManyField(to='ucportal.Course')),
            ],
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='forum_faculty_ID',
            field=models.ManyToManyField(to='ucportal.Faculty'),
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='forum_student_ID',
            field=models.ManyToManyField(to='ucportal.Student'),
        ),
    ]
